name: rrj_aquatique
description: "RRJ Aquatique: IoT-based fish aquarium monitoring and control system."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^5.1.0
  flutter_vector_icons: ^2.0.0

  # Firebase
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.3

  # State management
  provider: ^6.1.2

  # Charts
  fl_chart: ^0.63.0

  # HTTP
  http: 1.4.0

  # Date & Time formatting
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1

flutter:
  uses-material-design: true

  fonts:
    - family: SuperWater
      fonts:
        - asset: assets/fonts/SuperWater-PVoOm.ttf
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-VariableFont_wght.ttf

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/splash_logo.png"
  adaptive_icon_background: "#008080"
  adaptive_icon_foreground: "assets/images/splash_logo.png"
