import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'src/services/firestore_service.dart';
import 'package:provider/provider.dart';
import 'src/ui/screens/splash_screen.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

// Global navigator key for showing SnackBars
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

// Background notification handler
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  print("Handling background message: ${message.notification?.title}");
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Register background handler
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  // Run the app immediately
  runApp(
    MultiProvider(
      providers: [
        Provider(create: (_) => FirestoreService()),
      ],
      child: const MyApp(),
    ),
  );

  // Initialize FCM asynchronously (won’t block app startup)
  _initializeFCM().catchError((e) {
    print("FCM initialization error: $e");
  });
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      navigatorKey: navigatorKey,
      home: const SplashScreen(),
    );
  }
}

Future<void> _initializeFCM() async {
  try {
    final FirebaseMessaging messaging = FirebaseMessaging.instance;

    // Request permissions (required for iOS)
    await messaging.requestPermission(alert: true, badge: true, sound: true);

    // Get device FCM token
    final token = await messaging.getToken();
    print("Device FCM Token: $token");

    // Subscribe all devices to "alerts" topic
    await messaging.subscribeToTopic('alerts');
    print("✅ Subscribed to 'alerts' topic");

    // Save/update token in Firestore
    if (token != null) {
      await FirebaseFirestore.instance.collection('userTokens').doc(token).set({
        'token': token,
        'subscribedTo': 'alerts',
        'createdAt': FieldValue.serverTimestamp(),
      });
    }

    // Listen for messages while app is in foreground
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      if (message.notification != null && navigatorKey.currentContext != null) {
        final notification = message.notification!;
        ScaffoldMessenger.of(navigatorKey.currentContext!).showSnackBar(
          SnackBar(
            content: Text(notification.body ?? 'New notification received'),
            duration: const Duration(seconds: 3),
          ),
        );
      }
    });

    // Handle messages when app is opened from terminated state
    FirebaseMessaging.instance.getInitialMessage().then((message) {
      if (message != null) {
        print("App opened from terminated state via notification: ${message.notification?.title}");
      }
    });

    // Handle messages when app is opened from background
    FirebaseMessaging.onMessageOpenedApp.listen((message) {
      print("App opened from background via notification: ${message.notification?.title}");
    });
  } catch (e) {
    print("Error initializing FCM: $e");
  }
}
